dataset:
  name: "MassRoads"                     
  path: "/path/to/mass_roads/dataset"   
                                        
  read_data_file:
    # Supported file formats: [".tiff", ".tif", ".png", ".jpg", ".jpeg", ".h5", ".csv", ".json", ".txt", ".npy", ".npz"].
    file_format:                          
      input: ".tiff"                      # File format for input data.
      target: ".tif"                      # File format for target data.
      # If your file format is not supported in the list above, set "custom_read_file" to true
      # and implement a custom_read_file function to handle the unsupported format.
      custom_read_file: false             # Enable custom file handling for unsupported formats.
      # If additional parameters (**kwargs) need to be passed to the custom_read_file or read_file function, define them below.
      args:
        param1: "val1"                    # Example argument 1 for the custom or read function.
        param2: "val2"                    # Example argument 2 for the custom or read function.
        param3: "val3"                    # Example argument 3 for the custom or read function.


  split:                                
    train: "train"      # Path to the training dataset folder relative to the dataset path. If all data is in a single folder under the dataset path, specify a float ratio for splitting instead.
    val: "val"          # Path to the validation dataset folder relative to the dataset path. If all data is in a single folder under the dataset path, specify a float ratio for splitting instead.
    test: "test"        # Path to the test dataset folder relative to the dataset path. If all data is in a single folder under the dataset path, specify a float ratio for splitting instead.
    use_seed: true      # Enable deterministic splits by using a seed value.
    seed: 42            # Seed value for reproducible random splitting.
    shuffle: true       # Shuffle data before splitting.
    stratify: none
    custom_train_test_split: false  # Set to true if you want to implement a custom train-test split function.
    param1: "val1"     # Additional parameter for the custom split function (if custom_train_test_split is true).
    param2: "val2"     # Additional parameter for the custom split function (if custom_train_test_split is true).


preprocessing:
  enabled: true                        
  use_seed: true                       
  seed: 42                             
  operations:                          
    - name: "resize"                   
      enabled: true                    
      apply_to: "both"                 
      parameters:                      
        width: 512                     
        height: 512                    

    - name: "normalization"            
      enabled: true                    
      apply_to: "input"                
      parameters:
        method: "zscore"               
        range: [0, 1]                  
        mean: [0.485, 0.456, 0.406]    
        std: [0.229, 0.224, 0.225]     

    - name: "binarization"             
      enabled: true                    
      apply_to: "target"               
      parameters:
        threshold: 127                 

    - name: "sliding_window"           
      enabled: true                    
      apply_to: "both"                 
      parameters:
        window_size: 128               
        stride: 16                     
    
    - name: "custom_preprocess_input"
      enabled: true
      apply_to: "input"
      parameters:
        param1: "value1"
        param2: 42
    
    - name: "custom_preprocess_target"
      enabled: true
      apply_to: "target"
      parameters:
        param1: "value1"
        param2: 42

    - name: "custom_preprocess_both"
      enabled: true
      apply_to: "both"
      parameters:
        param1: "value1"
        param2: 42
        min_road_percentage: 0.05      
        small_window_size: 8    

augmentation:
  enabled: true                    
  use_seed: false                  
  seed: 42                         
  operations:                       
    - name: "random_flip"
      enabled: true                    
      apply_to: "both"
      
    - name: "random_rotation"
      enabled: true                    
      apply_to: "both"    
      parameters:
        angle: 15         

    - name: "color_jitter"
      enabled: true                    
      apply_to: "input" 
      parameters:
        brightness: 0.2          
        contrast: 0.2            
        saturation: 0.2          
        hue: 0.1                 

    - name: "custom_augmentations_input"
      enabled: true
      apply_to: "input"
      parameters:
        param1: "value1"
        param2: 42
    
    - name: "custom_augmentations_target"
      enabled: true
      apply_to: "target"
      parameters:
        param1: "value1"
        param2: 42

    - name: "custom_augmentations_both"
      enabled: true
      apply_to: "both"
      parameters:
        param1: "value1"
        param2: 42
        min_road_percentage: 0.05      
        small_window_size: 8    
          

loader:
  batch_size: 16                       
  num_workers: 4                      
  shuffle: true                         
  prefetch_factor: 2                   
  drop_last: false                      
  persistent_workers: true             
  use_seed: true                        
  seed: 42                             

logging:
  enabled: true                         
  log_path: "/path/to/logs"            
  verbosity: "info"                     

